### ISSUE TITLE
Error: transaction failed

### ISSUE THREAD

**Issue by nobita851** [nobita851/swap#2]
```
(node:262) UnhandledPromiseRejectionWarning: Error: transaction failed 
(transactionHash="0x96502c247a412447228d057e327e677eb13d9885eff7672cb8eacb7e593503d7", 
  transaction=
    {
      "nonce":5,
      "gasPrice":
      {
        "type":"BigNumber",
        "hex":"0x01dcd65000"
      },
      "gasLimit":
      {
        "type":"BigNumber",
        "hex":"0x061a80"
      },
      "to":"0xcedFebf9723C69723C6b13d4347a1704c10213BC12c338",
      "from":"0x01294db33459200211Be8115bD0913648D22e6FC",
      "contractAddress":null,
      "transactionIndex":29,
      "gasUsed":
      {
        "type":"BigNumber",
        "hex":"0x636d"
      },
      "logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "blockHash":"0xd72863f562fb185a49bc10b2d7d549a2bb5793ee3fd54b5da7d400d35f24c80f",
      "transactionHash":"0x96502c247a412447228d057e327e677eb13d9885eff7672cb8eacb7e593503d7",
      "logs":[],
      "blockNumber":15997437,
      "confirmations":1,
      "cumulativeGasUsed":
      {
        "type":"BigNumber",
        "hex":"0x6ddd5a"
      },
      "status":0,
      "type":0,
      "byzantium":true
  }
code=CALL_EXCEPTION, version=providers/5.5.2)    

at Logger.makeError (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/logger/lib/index.js:199:21)    
at Logger.throwError (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/logger/lib/index.js:208:20)    
at JsonRpcProvider.<anonymous> (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/providers/lib/base-provider.js:1492:36)      
at step (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
at Object.next (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
at fulfilled (/mnt/c/Users/Nobita/Desktop/HashStack/swap/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
(node:262) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:262) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

[Link to Code](https://github.com/nobita851/swap/blob/main/eths.js#L61)

**Comment by nobita851** [comment]
wBNB balance in contract Swap was 0, hence transaction is failing.
Error removed by funding contract Swap with wBNB tokens.
